//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.orderDetails = new HashSet<orderDetail>();
        }
    
        public int orderId { get; set; }
        public string orderNumber { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public int customerId { get; set; }
        public int paymentTypeId { get; set; }
        public decimal finalTotal { get; set; }
    
        public virtual ICollection<orderDetail> orderDetails { get; set; }
    }
}
